# Generated by Django 4.1.7 on 2023-03-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('re_password', models.CharField(max_length=50)),
                ('laptop', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('youtube', models.BooleanField()),
            ],
        ),
    ]
